alter table TEZISTEST_INVOICE add constraint FK_TEZISTEST_INVOICE_BUDGET_ITEM_ID foreign key (BUDGET_ITEM_ID) references TEZISTEST_BUDGET_ITEM(ID);
alter table TEZISTEST_INVOICE add constraint FK_TEZISTEST_INVOICE_CONTRACTOR_ID foreign key (CONTRACTOR_ID) references DF_COMPANY(CONTRACTOR_ID);
alter table TEZISTEST_INVOICE add constraint FK_TEZISTEST_INVOICE_CARD_ID foreign key (CARD_ID) references WF_CARD(ID);
create index IDX_TEZISTEST_INVOICE_CONTRACTOR on TEZISTEST_INVOICE (CONTRACTOR_ID);
create index IDX_TEZISTEST_INVOICE_BUDGET_ITEM on TEZISTEST_INVOICE (BUDGET_ITEM_ID);
