CREATE TABLE tezistest_ext_correspondent (
  CORRESPONDENT_ID UUID PRIMARY KEY,
  SIMPLE_DOC_ID UUID REFERENCES NOT NULL
)^

CONSTRAINT FK_TEZISTEST_EXT_CORRESPONDENT_SIMPLE_DOC FOREIGN KEY (SIMPLE_DOC_ID) REFERENCES DF_SIMPLE_DOC(CARD_ID)^